<a href="https://colab.research.google.com/github/Rahmatul-Rovi/Data-Mining-Lab-Tasks/blob/main/1st_Lab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# --- Part 1: 1D Array Slicing ---
arr = np.array([1, 2, 3, 4, 5])  # 1D array
print(arr)

print(arr[0])  # Output: 1
print(arr[0:2])  # Output: [1 2]
print(arr[0:5:2])  # Output: [1 3 5] (Starting index : ending index : step)
print(arr[:5])  # Output: [1 2 3 4 5]

# --- Part 2: 2D Array Slicing ---
arr1 = np.array([[1, 2, 3], [3, 4, 5], [7, 8, 9]])  # 2D Array
print(arr1)

print(arr1[0, 1])  # Row index 0, Col index 1 -> Output: 2
print(arr1[:, 2])  # All rows, Col index 2 -> Output: [3 5 9]
print(arr1[0:2, 0:2])  # First 2 rows and first 2 columns -> Output: [[1 2], [3 4]]
print(
    arr1[0:3:2, 0:3:2]
)  # Step 2 slicing -> Output: [[1 3], [7 9]] (Row 0, 2 & Col 0, 2)
print(arr1[0:2, 1:3])  # First 2 rows and last 2 columns -> Output: [[2 3], [4 5]]

# --- Part 3: Reshape Operations ---
arr_reshape = np.array([1, 2, 3, 4, 5, 6])  # 1D array with 6 elements
print(arr_reshape)

# 2 Rows, 3 Columns
newarr1 = arr_reshape.reshape(2, 3)
print(newarr1)

# 3 Rows, 2 Columns
newarr2 = arr_reshape.reshape(3, 2)
print(newarr2)

# 1 Row, 6 Columns (2D array format)
newarr3 = arr_reshape.reshape(1, 6)
print(newarr3)

# --- Part 4: 3D Reshape Fix ---
# 6 elements cannot be reshaped to (3, 2, 2) which requires 3*2*2 = 12 elements.
# Changing to (3, 2, 1) or changing the input array size to 12.
ar1 = arr_reshape.reshape(3, 2, 1)  # 3 blocks, 2 rows, 1 column
print(ar1)

[1 2 3 4 5]
1
[1 2]
[1 3 5]
[1 2 3 4 5]
[[1 2 3]
 [3 4 5]
 [7 8 9]]
2
[3 5 9]
[[1 2]
 [3 4]]
[[1 3]
 [7 9]]
[[2 3]
 [4 5]]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2 3 4 5 6]]
[[[1]
  [2]]

 [[3]
  [4]]

 [[5]
  [6]]]


In [ ]:
# Extract element 10 from the above 3d array

# Extract 2nd Matrix

# Extract 2nd row, 3rd column of matrix 1

import numpy as np

arr = np.array([[[1, 2], [3, 4], [5, 6]], [[7, 8], [9, 10], [11, 12]]])

# Answer 1:
print(arr[1, 1, 1])

# Answer 2:
print(arr[1])

# Matrix 1 3rd row (index 2) and 2nd column (index 1):
print(arr[0, 2, 1])


10
[[ 7  8]
 [ 9 10]
 [11 12]]
6


In [ ]:
import numpy as np

marks = np.array([55, 60, 72, 80, 85, 90, 95])

print("Mean:", np.mean(marks))
print("Median:", np.median(marks))
print("Std:", np.std(marks))
print("Q1:", np.percentile(marks, 25))
print("Q3:", np.percentile(marks, 75))

Mean: 76.71428571428571
Median: 80.0
Std: 13.95619970493693
Q1: 66.0
Q3: 87.5


In [ ]:
#print the outlier using the iqr range

import numpy as np

marks = np.array([55, 60, 72, 80, 85, 90, 95])

# Calculate Q1 and Q3
Q1 = np.percentile(marks, 25)
Q3 = np.percentile(marks, 75)

# Calculate IQR
IQR = Q3 - Q1
print("IQR:", IQR)

# Calculate outlier boundaries
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

print("Lower bound:", lower_bound)
print("Upper bound:", upper_bound)

# Find outliers
outliers = marks[(marks < lower_bound) | (marks > upper_bound)]

print("Outliers:", outliers)


IQR: 21.5
Lower bound: 33.75
Upper bound: 119.75
Outliers: []
