<a href="https://colab.research.google.com/github/Rahmatul-Rovi/Data-Mining-Lab-Tasks/blob/main/Data_Mining.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# --- Part 1: 1D Array Slicing ---
arr = np.array([1, 2, 3, 4, 5])  # 1D array
print(arr)

print(arr[0])  # Output: 1
print(arr[0:2])  # Output: [1 2]
print(arr[0:5:2])  # Output: [1 3 5] (Starting index : ending index : step)
print(arr[:5])  # Output: [1 2 3 4 5]

# --- Part 2: 2D Array Slicing ---
arr1 = np.array([[1, 2, 3], [3, 4, 5], [7, 8, 9]])  # 2D Array
print(arr1)

print(arr1[0, 1])  # Row index 0, Col index 1 -> Output: 2
print(arr1[:, 2])  # All rows, Col index 2 -> Output: [3 5 9]
print(arr1[0:2, 0:2])  # First 2 rows and first 2 columns -> Output: [[1 2], [3 4]]
print(
    arr1[0:3:2, 0:3:2]
)  # Step 2 slicing -> Output: [[1 3], [7 9]] (Row 0, 2 & Col 0, 2)
print(arr1[0:2, 1:3])  # First 2 rows and last 2 columns -> Output: [[2 3], [4 5]]

# --- Part 3: Reshape Operations ---
arr_reshape = np.array([1, 2, 3, 4, 5, 6])  # 1D array with 6 elements
print(arr_reshape)

# 2 Rows, 3 Columns
newarr1 = arr_reshape.reshape(2, 3)
print(newarr1)

# 3 Rows, 2 Columns
newarr2 = arr_reshape.reshape(3, 2)
print(newarr2)

# 1 Row, 6 Columns (2D array format)
newarr3 = arr_reshape.reshape(1, 6)
print(newarr3)

# --- Part 4: 3D Reshape Fix ---
# 6 elements cannot be reshaped to (3, 2, 2) which requires 3*2*2 = 12 elements.
# Changing to (3, 2, 1) or changing the input array size to 12.
ar1 = arr_reshape.reshape(3, 2, 1)  # 3 blocks, 2 rows, 1 column
print(ar1)

[1 2 3 4 5]
1
[1 2]
[1 3 5]
[1 2 3 4 5]
[[1 2 3]
 [3 4 5]
 [7 8 9]]
2
[3 5 9]
[[1 2]
 [3 4]]
[[1 3]
 [7 9]]
[[2 3]
 [4 5]]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2 3 4 5 6]]
[[[1]
  [2]]

 [[3]
  [4]]

 [[5]
  [6]]]


In [ ]:
# Extract element 10 from the above 3d array

# Extract 2nd Matrix

# Extract 2nd row, 3rd column of matrix 1

import numpy as np

arr = np.array([[[1, 2], [3, 4], [5, 6]], [[7, 8], [9, 10], [11, 12]]])

# Answer 1:
print(arr[1, 1, 1])

# Answer 2:
print(arr[1])

# Matrix 1 3rd row (index 2) and 2nd column (index 1):
print(arr[0, 2, 1])


10
[[ 7  8]
 [ 9 10]
 [11 12]]
6


In [ ]:
import numpy as np

marks = np.array([55, 60, 72, 80, 85, 90, 95])

print("Mean:", np.mean(marks))
print("Median:", np.median(marks))
print("Std:", np.std(marks))
print("Q1:", np.percentile(marks, 25))
print("Q3:", np.percentile(marks, 75))

Mean: 76.71428571428571
Median: 80.0
Std: 13.95619970493693
Q1: 66.0
Q3: 87.5


In [ ]:
#print the outlier using the iqr range

import numpy as np

marks = np.array([55, 60, 72, 80, 85, 90, 95])

# Calculate Q1 and Q3
Q1 = np.percentile(marks, 25)
Q3 = np.percentile(marks, 75)

# Calculate IQR
IQR = Q3 - Q1
print("IQR:", IQR)

# Calculate outlier boundaries
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

print("Lower bound:", lower_bound)
print("Upper bound:", upper_bound)

# Find outliers
outliers = marks[(marks < lower_bound) | (marks > upper_bound)]

print("Outliers:", outliers)


IQR: 21.5
Lower bound: 33.75
Upper bound: 119.75
Outliers: []


In [ ]:
#2nd Lab

In [ ]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.full((3,4), 5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [ ]:
np.arange(1,15)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
import pandas as pd
df=pd.DataFrame({
    'Student':['A', 'B', 'C', 'D'],
    'Math': [80,82, 40, 20],
    'CSE':[70,72,50,25],
    'English': [90,88, 45, 15],
    'Grade': ['A', 'A', 'B', 'C']
})
print(df)

  Student  Math  CSE  English Grade
0       A    80   70       90     A
1       B    82   72       88     A
2       C    40   50       45     B
3       D    20   25       15     C


In [ ]:
features = df[['Math', 'CSE', 'English']].values
print(features)
print(len(features))
A= features[0]
B= features[1]
manhattan = np.sum(np.abs(A-B))
print(manhattan)

[[80 70 90]
 [82 72 88]
 [40 50 45]
 [20 25 15]]
4
6


In [ ]:
num_features = len(features)
distance_matrix = np.zeros((num_features, num_features))

for i in range(num_features):
    for j in range(num_features):
        distance = np.sum(np.abs(features[i] - features[j]))
        distance_matrix[i][j] = distance

print(distance_matrix)

[[  0.   6. 105. 180.]
 [  6.   0. 107. 182.]
 [105. 107.   0.  75.]
 [180. 182.  75.   0.]]


In [ ]:
import numpy as np

num_features = len(features)
distance_matrix = np.zeros((num_features, num_features))

for i in range(num_features):
    for j in range(num_features):
        # Euclidean Distance: np.sqrt(np.sum((a - b)**2)) or np.linalg.norm(a - b)
        distance = np.sqrt(np.sum((features[i] - features[j]) ** 2))
        distance_matrix[i][j] = distance

print(distance_matrix)

[[  0.           3.46410162  63.4428877  106.06601718]
 [  3.46410162   0.          64.00781202 106.6864565 ]
 [ 63.4428877   64.00781202   0.          43.87482194]
 [106.06601718 106.6864565   43.87482194   0.        ]]


In [ ]:
import numpy as np
import pandas as pd

df = pd.DataFrame({
    'Student': ['A', 'B', 'C', 'D'],
    'Math': [80, 82, 40, 20],
    'CSE': [70, 72, 50, 25],
    'English': [90, 88, 45, 15],
    'Grade': ['A', 'A', 'B', 'C'],
})

num_students = len(df)
nominal_matrix = np.zeros((num_students, num_students))
grades = df['Grade'].values

for i in range(num_students):
    for j in range(num_students):

        nominal_matrix[i][j] = 1 if grades[i] != grades[j] else 0

print('Nominal Distance Matrix (Grade):')
print(
    pd.DataFrame(
        nominal_matrix, index=df['Student'], columns=df['Student']
    )
)

Nominal Distance Matrix (Grade):
Student    A    B    C    D
Student                    
A        0.0  0.0  1.0  1.0
B        0.0  0.0  1.0  1.0
C        1.0  1.0  0.0  1.0
D        1.0  1.0  1.0  0.0


In [ ]:
# Rank mapping for Ordinal Grade
grade_rank = {'A': 0, 'B': 1, 'C': 2}
ranks = df['Grade'].map(grade_rank).values
max_rank = max(grade_rank.values()) - min(grade_rank.values())  # 2 - 0 = 2

ordinal_matrix = np.zeros((num_students, num_students))

for i in range(num_students):
    for j in range(num_students):

        ordinal_matrix[i][j] = abs(ranks[i] - ranks[j]) / max_rank

print('Ordinal Distance Matrix (Grade):')
print(
    pd.DataFrame(
        ordinal_matrix, index=df['Student'], columns=df['Student']
    )
)

Ordinal Distance Matrix (Grade):
Student    A    B    C    D
Student                    
A        0.0  0.0  0.5  1.0
B        0.0  0.0  0.5  1.0
C        0.5  0.5  0.0  0.5
D        1.0  1.0  0.5  0.0


In [ ]:
import numpy as np
X = np.array([[1, 2],
              [3, 4],
              [5, 6]])

In [ ]:
lst = [1, 2, 3]
arr = np.array([1, 2, 3])

print(lst * 2)   # [1,2,3,1,2,3]
print(arr * 2)   # [2 4 6]

[1, 2, 3, 1, 2, 3]
[2 4 6]


In [ ]:
W = np.array([[0.2], [0.5]])
X = np.array([[1, 2]])

output = np.dot(X, W)
print(output)

[[1.2]]


In [ ]:
import numpy as np
arr = np.array((1, 2, 3, 4, 5))
print(arr)

[1 2 3 4 5]


In [ ]:
print(type(arr))
print(arr.dtype)

<class 'numpy.ndarray'>
int64


In [ ]:
arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5]) # 1d array
print(arr)
print(arr[0])
print(arr[0:5])

[1 2 3 4 5]
1
[1 2 3 4 5]


In [ ]:
arr1 = np.array([[1,2,3],[3,4,6],[7,8,9]]) # 2d array
print(arr1.shape)

(3, 3)


In [ ]:
arr2 = np.array([[[1,2,3],[3,4,6],[7,8,9]],[[3,6,7],[8,9,10],[2,6,8]]]) # 3d array
print(arr2.shape)
print(arr2)
# Create a 3d array
# Extract first row of the first matrix
# Extract first two rows of the second matrix
print(arr2[1,0:2,:])
# Extract last two columns of the first matrix

(2, 3, 3)
[[[ 1  2  3]
  [ 3  4  6]
  [ 7  8  9]]

 [[ 3  6  7]
  [ 8  9 10]
  [ 2  6  8]]]
[[ 3  6  7]
 [ 8  9 10]]


In [ ]:
# Array Reshaping
arr = np.arange(1,13)
print(arr)
# Reshape the 1d array to 2d array in all possible combinations
arr1 = arr.reshape(6,2)
# Reshape the 1d array to 3d array in all possible combinations


[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
print(arr1[0])


[1 2]


In [ ]:
mat = np.zeros((3, 4))


In [ ]:
np.ones((2, 3))


array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.full((2, 3), 7)


array([[7, 7, 7],
       [7, 7, 7]])

In [ ]:
np.arange(1, 20)


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [ ]:
np.linspace(0, 1, 5)


array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
np.eye(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
print(arr1[0:3:2,0:3:2])


[[1]
 [5]]


In [ ]:
# Extract 2nd row
print(arr1[1,0:3])
# extract 3rd column
print(arr1[0:3,2])
# Extract first two rows and last two columns
print(arr1[0:2,1:3])

[3 4]


IndexError: index 2 is out of bounds for axis 1 with size 2